const quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
  "The best way to predict the future is to create it. - Peter Drucker",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The secret of getting ahead is getting started. - Mark Twain",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "The biggest risk is not taking any risk. In a world that is changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The successful man is the one who finds out what is the matter with his business before his competitors do. - Roy L. Smith",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "The best revenge is massive success. - Frank Sinatra",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "The successful person makes a habit of doing what the failing person doesn't like to do. - Thomas Edison",
  "Your work is discover your work and then with all your heart to give yourself to it. - Buddha",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "The starting point of all achievement is desire. - Napoleon Hill",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
  "The harder I work, the luckier I get. - Gary Player",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "If you want to achieve greatness stop asking for permission. - Anonymous",
  "The biggest risk is not taking any risk. In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
  "The successful person makes a habit of doing what the failing person doesn't like to do. - Thomas Edison",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The best way to predict the future is to create it. - Peter Drucker",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The successful man is the one who finds out what is the matter with his business before his competitors do. - Roy L. Smith",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "The best revenge is massive success. - Frank Sinatra",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The starting point of all achievement is desire. - Napoleon Hill",
  "Your work is discover your work and then with all your heart to give yourself to it. - Buddha",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "The harder I work, the luckier I get. - Gary Player",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "If you want to achieve greatness stop asking for permission. - Anonymous",
  "The biggest risk is not taking any risk. In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
  "The successful person makes a habit of doing what the failing person doesn't like to do. - Thomas Edison",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The best way to predict the future is to create it. - Peter Drucker",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The successful man is the one who finds out what is the matter with his business before his competitors do. - Roy L. Smith",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "The best revenge is massive success. - Frank Sinatra",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The starting point of all achievement is desire. - Napoleon Hill",
  "Your work is discover your work and then with all your heart to give yourself to it. - Buddha",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "The harder I work, the luckier I get. - Gary Player",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "If you want to achieve greatness stop asking for permission. - Anonymous",
  "The biggest risk is not taking any risk. In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
  "The successful person makes a habit of doing what the failing person doesn't like to do. - Thomas Edison",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The best way to predict the future is to create it. - Peter Drucker",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The successful man is the one who finds out what is the matter with his business before his competitors do. - Roy L. Smith",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "The best revenge is massive success. - Frank Sinatra",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The starting point of all achievement is desire. - Napoleon Hill",
  "Your work is discover your work and then with all your heart to give yourself to it. - Buddha",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "The harder I work, the luckier I get. - Gary Player",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "If you want to achieve greatness stop asking for permission. - Anonymous",
  "The biggest risk is not taking any risk. In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
  "The successful person makes a habit of doing what the failing person doesn't like to do. - Thomas Edison",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The best way to predict the future is to create it. - Peter Drucker",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The successful man is the one who finds out what is the matter with his business before his competitors do. - Roy L. Smith",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "The best revenge is massive success. - Frank Sinatra",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The starting point of all achievement is desire. - Napoleon Hill",
  "Your work is discover your work and then with all your heart to give yourself to it. - Buddha",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "The harder I work, the luckier I get. - Gary Player",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "If you want to achieve greatness stop asking for permission. - Anonymous",
  "The biggest risk is not taking any risk. In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
  "The successful person makes a habit of doing what the failing person doesn't like to do. - Thomas Edison",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The best way to predict the future is to create it. - Peter Drucker",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "The successful man is the one who finds out what is the matter with his business before his competitors do. - Roy L. Smith",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "The best revenge is massive success. - Frank Sinatra",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "The starting point of all achievement is desire. - Napoleon Hill",
  "Your work is discover your work and then with all your heart to give yourself to it. - Buddha",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "The harder I work, the luckier I get. - Gary Player",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "If you want to achieve greatness stop asking for permission. - Anonymous",
  "The biggest risk is not taking any risk. In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
];

const quoteElem = document.getElementById("quote");
const generateBtn = document.getElementById("generate-btn");
const copyBtn = document.getElementById("copy-btn");

generateBtn.addEventListener("click", generateQuote);
copyBtn.addEventListener("click", copyQuote);

function generateQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  const randomQuote = quotes[randomIndex];
  quoteElem.textContent = randomQuote;
}

function copyQuote() {
  const quoteText = quoteElem.textContent;

  // Create a temporary input element
  const tempInput = document.createElement("textarea");
  tempInput.value = quoteText;
  document.body.appendChild(tempInput);

  // Select the text in the input element
  tempInput.select();
  tempInput.setSelectionRange(0, 99999); // For mobile devices

  // Copy the text to the clipboard
  document.execCommand("copy");

  // Remove the temporary input element
  document.body.removeChild(tempInput);

  // Alert the user
  alert("Quote copied to clipboard!");
}
